class Node:
    serial: int | None
    ant_version: str | None
    max_channels: int

    def __init__(self) -> None: ...
    def set_network_key(self, network: int, key: list[int]) -> object: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

